{{- if .Values.registry.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.registry.imagePullSecret }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
