{{- if .Values.rbac.enabled -}}
# create rbac role with permission for discovery
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "allure-testops.name" . }}-namespace-reader
  labels:
    app: {{ template "allure-testops.name" . }}
    chart: {{ template "allure-testops.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
{{ toYaml .Values.rbac.rules | indent 2}}
{{- end -}}
