{{- if .Values.rbac.enabled -}}
# bind this rbac role to default ServiceAccount in your namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "allure-testops.name" . }}-namespace-reader
  labels:
    app: {{ template "allure-testops.name" . }}
    chart: {{ template "allure-testops.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ template "allure-testops.name" . }}-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "allure-testops.name" . }}-namespace-reader
{{- end -}}
